name: Run Python Script on Commit

on:
  push:
    paths:
      - 'src/alertes.csv'  # Path to the file that triggers the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute py script
        run: |
            python src/alerte_to_alerte_par_jour_script.py
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)
            
      - name: Push Changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}