name: Run Python Script on Commit

on:
  push:
    paths:
      - 'src/alertes.csv'  # Path to the file that triggers the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute py script
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            python src/alerte_to_alerte_par_jour_script.py
            git config --local user.name "${{ github.actor }}"
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git commit -am "Fichier alerte_par_jours.csv mis à jour" || echo "There is nothing to commit"
            git push

